// Country and state data for dropdown selection
class CountryStateData {
  // Localized country names
  static final Map<String, Map<String, String>> localizedCountryNames = {
    'en': {
      'US': 'United States',
      'CA': 'Canada',
      'GB': 'United Kingdom',
      'AU': 'Australia',
      'DE': 'Germany',
      'FR': 'France',
      'IT': 'Italy',
      'ES': 'Spain',
      'JP': 'Japan',
      'CN': 'China',
      'IN': 'India',
      'BR': 'Brazil',
      'RU': 'Russia',
      'ZA': 'South Africa',
      'EG': 'Egypt',
      'SA': 'Saudi Arabia',
      'AE': 'United Arab Emirates',
      'TN': 'Tunisia',
      'DZ': 'Algeria',
      'MA': 'Morocco',
      'LY': 'Libya',
    },
    'ar': {
      'US': 'الولايات المتحدة',
      'CA': 'كندا',
      'GB': 'المملكة المتحدة',
      'AU': 'أستراليا',
      'DE': 'ألمانيا',
      'FR': 'فرنسا',
      'IT': 'إيطاليا',
      'ES': 'إسبانيا',
      'JP': 'اليابان',
      'CN': 'الصين',
      'IN': 'الهند',
      'BR': 'البرازيل',
      'RU': 'روسيا',
      'ZA': 'جنوب أفريقيا',
      'EG': 'مصر',
      'SA': 'المملكة العربية السعودية',
      'AE': 'الإمارات العربية المتحدة',
      'TN': 'تونس',
      'DZ': 'الجزائر',
      'MA': 'المغرب',
      'LY': 'ليبيا',
    },
    'fr': {
      'US': 'États-Unis',
      'CA': 'Canada',
      'GB': 'Royaume-Uni',
      'AU': 'Australie',
      'DE': 'Allemagne',
      'FR': 'France',
      'IT': 'Italie',
      'ES': 'Espagne',
      'JP': 'Japon',
      'CN': 'Chine',
      'IN': 'Inde',
      'BR': 'Brésil',
      'RU': 'Russie',
      'ZA': 'Afrique du Sud',
      'EG': 'Égypte',
      'SA': 'Arabie Saoudite',
      'AE': 'Émirats Arabes Unis',
      'TN': 'Tunisie',
      'DZ': 'Algérie',
      'MA': 'Maroc',
      'LY': 'Libye',
    },
  };

  static final List<Map<String, dynamic>> countries = [
    {
      'name': 'United States',
      'code': 'US',
      'states': [
        'Alabama',
        'Alaska',
        'Arizona',
        'Arkansas',
        'California',
        'Colorado',
        'Connecticut',
        'Delaware',
        'Florida',
        'Georgia',
        'Hawaii',
        'Idaho',
        'Illinois',
        'Indiana',
        'Iowa',
        'Kansas',
        'Kentucky',
        'Louisiana',
        'Maine',
        'Maryland',
        'Massachusetts',
        'Michigan',
        'Minnesota',
        'Mississippi',
        'Missouri',
        'Montana',
        'Nebraska',
        'Nevada',
        'New Hampshire',
        'New Jersey',
        'New Mexico',
        'New York',
        'North Carolina',
        'North Dakota',
        'Ohio',
        'Oklahoma',
        'Oregon',
        'Pennsylvania',
        'Rhode Island',
        'South Carolina',
        'South Dakota',
        'Tennessee',
        'Texas',
        'Utah',
        'Vermont',
        'Virginia',
        'Washington',
        'West Virginia',
        'Wisconsin',
        'Wyoming',
      ],
    },
    {
      'name': 'Canada',
      'code': 'CA',
      'states': [
        'Alberta',
        'British Columbia',
        'Manitoba',
        'New Brunswick',
        'Newfoundland and Labrador',
        'Northwest Territories',
        'Nova Scotia',
        'Nunavut',
        'Ontario',
        'Prince Edward Island',
        'Quebec',
        'Saskatchewan',
        'Yukon',
      ],
    },
    {
      'name': 'United Kingdom',
      'code': 'GB',
      'states': ['England', 'Northern Ireland', 'Scotland', 'Wales'],
    },
    {
      'name': 'Australia',
      'code': 'AU',
      'states': [
        'Australian Capital Territory',
        'New South Wales',
        'Northern Territory',
        'Queensland',
        'South Australia',
        'Tasmania',
        'Victoria',
        'Western Australia',
      ],
    },
    {
      'name': 'Germany',
      'code': 'DE',
      'states': [
        'Baden-Württemberg',
        'Bavaria',
        'Berlin',
        'Brandenburg',
        'Bremen',
        'Hamburg',
        'Hesse',
        'Lower Saxony',
        'Mecklenburg-Vorpommern',
        'North Rhine-Westphalia',
        'Rhineland-Palatinate',
        'Saarland',
        'Saxony',
        'Saxony-Anhalt',
        'Schleswig-Holstein',
        'Thuringia',
      ],
    },
    {
      'name': 'France',
      'code': 'FR',
      'states': [
        'Auvergne-Rhône-Alpes',
        'Bourgogne-Franche-Comté',
        'Brittany',
        'Centre-Val de Loire',
        'Corsica',
        'Grand Est',
        'Hauts-de-France',
        'Île-de-France',
        'Normandy',
        'Nouvelle-Aquitaine',
        'Occitanie',
        'Pays de la Loire',
        'Provence-Alpes-Côte d\'Azur',
      ],
    },
    {
      'name': 'Italy',
      'code': 'IT',
      'states': [
        'Abruzzo',
        'Aosta Valley',
        'Apulia',
        'Basilicata',
        'Calabria',
        'Campania',
        'Emilia-Romagna',
        'Friuli Venezia Giulia',
        'Lazio',
        'Liguria',
        'Lombardy',
        'Marche',
        'Molise',
        'Piedmont',
        'Sardinia',
        'Sicily',
        'Trentino-South Tyrol',
        'Tuscany',
        'Umbria',
        'Veneto',
      ],
    },
    {
      'name': 'Spain',
      'code': 'ES',
      'states': [
        'Andalusia',
        'Aragon',
        'Asturias',
        'Balearic Islands',
        'Basque Country',
        'Canary Islands',
        'Cantabria',
        'Castile and León',
        'Castilla-La Mancha',
        'Catalonia',
        'Extremadura',
        'Galicia',
        'La Rioja',
        'Madrid',
        'Murcia',
        'Navarre',
        'Valencia',
      ],
    },
    {
      'name': 'Japan',
      'code': 'JP',
      'states': [
        'Aichi',
        'Akita',
        'Aomori',
        'Chiba',
        'Ehime',
        'Fukui',
        'Fukuoka',
        'Fukushima',
        'Gifu',
        'Gunma',
        'Hiroshima',
        'Hokkaido',
        'Hyogo',
        'Ibaraki',
        'Ishikawa',
        'Iwate',
        'Kagawa',
        'Kagoshima',
        'Kanagawa',
        'Kochi',
        'Kumamoto',
        'Kyoto',
        'Mie',
        'Miyagi',
        'Miyazaki',
        'Nagano',
        'Nagasaki',
        'Nara',
        'Niigata',
        'Oita',
        'Okayama',
        'Okinawa',
        'Osaka',
        'Saga',
        'Saitama',
        'Shiga',
        'Shimane',
        'Shizuoka',
        'Tochigi',
        'Tokushima',
        'Tokyo',
        'Tottori',
        'Toyama',
        'Wakayama',
        'Yamagata',
        'Yamaguchi',
        'Yamanashi',
      ],
    },
    {
      'name': 'China',
      'code': 'CN',
      'states': [
        'Anhui',
        'Beijing',
        'Chongqing',
        'Fujian',
        'Gansu',
        'Guangdong',
        'Guangxi',
        'Guizhou',
        'Hainan',
        'Hebei',
        'Heilongjiang',
        'Henan',
        'Hong Kong',
        'Hubei',
        'Hunan',
        'Inner Mongolia',
        'Jiangsu',
        'Jiangxi',
        'Jilin',
        'Liaoning',
        'Macau',
        'Ningxia',
        'Qinghai',
        'Shaanxi',
        'Shandong',
        'Shanghai',
        'Shanxi',
        'Sichuan',
        'Taiwan',
        'Tianjin',
        'Tibet',
        'Xinjiang',
        'Yunnan',
        'Zhejiang',
      ],
    },
    {
      'name': 'India',
      'code': 'IN',
      'states': [
        'Andhra Pradesh',
        'Arunachal Pradesh',
        'Assam',
        'Bihar',
        'Chhattisgarh',
        'Goa',
        'Gujarat',
        'Haryana',
        'Himachal Pradesh',
        'Jharkhand',
        'Karnataka',
        'Kerala',
        'Madhya Pradesh',
        'Maharashtra',
        'Manipur',
        'Meghalaya',
        'Mizoram',
        'Nagaland',
        'Odisha',
        'Punjab',
        'Rajasthan',
        'Sikkim',
        'Tamil Nadu',
        'Telangana',
        'Tripura',
        'Uttar Pradesh',
        'Uttarakhand',
        'West Bengal',
      ],
    },
    {
      'name': 'Brazil',
      'code': 'BR',
      'states': [
        'Acre',
        'Alagoas',
        'Amapá',
        'Amazonas',
        'Bahia',
        'Ceará',
        'Distrito Federal',
        'Espírito Santo',
        'Goiás',
        'Maranhão',
        'Mato Grosso',
        'Mato Grosso do Sul',
        'Minas Gerais',
        'Pará',
        'Paraíba',
        'Paraná',
        'Pernambuco',
        'Piauí',
        'Rio de Janeiro',
        'Rio Grande do Norte',
        'Rio Grande do Sul',
        'Rondônia',
        'Roraima',
        'Santa Catarina',
        'São Paulo',
        'Sergipe',
        'Tocantins',
      ],
    },
    {
      'name': 'Russia',
      'code': 'RU',
      'states': [
        'Adygea',
        'Altai Krai',
        'Altai Republic',
        'Amur Oblast',
        'Arkhangelsk Oblast',
        'Astrakhan Oblast',
        'Bashkortostan',
        'Belgorod Oblast',
        'Bryansk Oblast',
        'Buryatia',
        'Chechen Republic',
        'Chelyabinsk Oblast',
        'Chukotka Autonomous Okrug',
        'Chuvashia',
        'Dagestan',
        'Ingushetia',
        'Irkutsk Oblast',
        'Ivanovo Oblast',
        'Jewish Autonomous Oblast',
        'Kabardino-Balkaria',
        'Kaliningrad Oblast',
        'Kalmykia',
        'Kaluga Oblast',
        'Kamchatka Krai',
        'Karachay-Cherkessia',
        'Karelia',
        'Kemerovo Oblast',
        'Khabarovsk Krai',
        'Khakassia',
        'Khanty-Mansi',
        'Kirov Oblast',
        'Komi',
        'Kostroma Oblast',
        'Krasnodar Krai',
        'Krasnoyarsk Krai',
        'Kurgan Oblast',
        'Kursk Oblast',
        'Leningrad Oblast',
        'Lipetsk Oblast',
        'Magadan Oblast',
        'Mari El',
        'Mordovia',
        'Moscow',
        'Moscow Oblast',
        'Murmansk Oblast',
        'Nenets Autonomous Okrug',
        'Nizhny Novgorod Oblast',
        'North Ossetia-Alania',
        'Novgorod Oblast',
        'Novosibirsk Oblast',
        'Omsk Oblast',
        'Orenburg Oblast',
        'Oryol Oblast',
        'Penza Oblast',
        'Perm Krai',
        'Primorsky Krai',
        'Pskov Oblast',
        'Rostov Oblast',
        'Ryazan Oblast',
        'Saint Petersburg',
        'Sakha Republic',
        'Sakhalin Oblast',
        'Samara Oblast',
        'Saratov Oblast',
        'Sevastopol',
        'Smolensk Oblast',
        'Stavropol Krai',
        'Sverdlovsk Oblast',
        'Tambov Oblast',
        'Tatarstan',
        'Tomsk Oblast',
        'Tula Oblast',
        'Tver Oblast',
        'Tyumen Oblast',
        'Tyva',
        'Udmurtia',
        'Ulyanovsk Oblast',
        'Vladimir Oblast',
        'Volgograd Oblast',
        'Vologda Oblast',
        'Voronezh Oblast',
        'Yamalo-Nenets',
        'Yaroslavl Oblast',
        'Zabaykalsky Krai',
      ],
    },
    {
      'name': 'South Africa',
      'code': 'ZA',
      'states': [
        'Eastern Cape',
        'Free State',
        'Gauteng',
        'KwaZulu-Natal',
        'Limpopo',
        'Mpumalanga',
        'North West',
        'Northern Cape',
        'Western Cape',
      ],
    },
    {
      'name': 'Egypt',
      'code': 'EG',
      'states': [
        'Alexandria',
        'Aswan',
        'Asyut',
        'Beheira',
        'Beni Suef',
        'Cairo',
        'Dakahlia',
        'Damietta',
        'Faiyum',
        'Gharbia',
        'Giza',
        'Ismailia',
        'Kafr El Sheikh',
        'Luxor',
        'Matruh',
        'Minya',
        'Monufia',
        'New Valley',
        'North Sinai',
        'Port Said',
        'Qalyubia',
        'Qena',
        'Red Sea',
        'Sharqia',
        'Sohag',
        'South Sinai',
        'Suez',
      ],
    },
    {
      'name': 'Saudi Arabia',
      'code': 'SA',
      'states': [
        'Asir',
        'Bahah',
        'Eastern Province',
        'Hail',
        'Jazan',
        'Jawf',
        'Jizan',
        'Madinah',
        'Makkah',
        'Najran',
        'Northern Borders',
        'Qassim',
        'Riyadh',
        'Tabuk',
      ],
    },
    {
      'name': 'United Arab Emirates',
      'code': 'AE',
      'states': [
        'Abu Dhabi',
        'Ajman',
        'Dubai',
        'Fujairah',
        'Ras Al Khaimah',
        'Sharjah',
        'Umm Al Quwain',
      ],
    },
    {
      'name': 'Tunisia',
      'code': 'TN',
      'states': [
        'Ariana',
        'Béja',
        'Ben Arous',
        'Bizerte',
        'Gabès',
        'Gafsa',
        'Jendouba',
        'Kairouan',
        'Kasserine',
        'Kebili',
        'Kef',
        'Mahdia',
        'Manouba',
        'Medenine',
        'Monastir',
        'Nabeul',
        'Sfax',
        'Sidi Bouzid',
        'Siliana',
        'Sousse',
        'Tataouine',
        'Tozeur',
        'Tunis',
        'Zaghouan',
      ],
    },
    {
      'name': 'Algeria',
      'code': 'DZ',
      'states': [
        'Adrar',
        'Aïn Defla',
        'Aïn Témouchent',
        'Algiers',
        'Annaba',
        'Batna',
        'Béchar',
        'Béjaïa',
        'Biskra',
        'Blida',
        'Bordj Bou Arréridj',
        'Bouira',
        'Boumerdès',
        'Chlef',
        'Constantine',
        'Djelfa',
        'El Bayadh',
        'El Oued',
        'El Tarf',
        'Ghardaïa',
        'Guelma',
        'Illizi',
        'Jijel',
        'Khenchela',
        'Laghouat',
        'Mascara',
        'Médéa',
        'Mila',
        'Mostaganem',
        'M\'Sila',
        'Naâma',
        'Oran',
        'Ouargla',
        'Oum El Bouaghi',
        'Relizane',
        'Saïda',
        'Sétif',
        'Sidi Bel Abbès',
        'Skikda',
        'Souk Ahras',
        'Tamanrasset',
        'Tébessa',
        'Tiaret',
        'Tindouf',
        'Tipaza',
        'Tissemsilt',
        'Tizi Ouzou',
        'Tlemcen',
      ],
    },
    {
      'name': 'Morocco',
      'code': 'MA',
      'states': [
        'Béni Mellal-Khénifra',
        'Casablanca-Settat',
        'Drâa-Tafilalet',
        'Fès-Meknès',
        'Guelmim-Oued Noun',
        'Laâyoune-Sakia El Hamra',
        'Marrakech-Safi',
        'Oriental',
        'Rabat-Salé-Kénitra',
        'Souss-Massa',
        'Tanger-Tétouan-Al Hoceïma',
      ],
    },
    {
      'name': 'Libya',
      'code': 'LY',
      'states': [
        'Al Wahat',
        'Benghazi',
        'Derna',
        'Ghat',
        'Jabal al Akhdar',
        'Jabal al Gharbi',
        'Jafara',
        'Jufra',
        'Kufra',
        'Marj',
        'Misrata',
        'Murqub',
        'Murzuq',
        'Nalut',
        'Nuqat al Khams',
        'Sabha',
        'Sirte',
        'Tripoli',
        'Wadi al Hayaa',
        'Wadi al Shatii',
        'Zawiya',
      ],
    },
  ];

  // Get states for a given country
  static List<String> getStatesForCountry(String countryName) {
    final country = countries.firstWhere(
      (c) => c['name'] == countryName,
      orElse: () => {'states': <String>[]},
    );
    return List<String>.from(country['states'] ?? []);
  }

  // Get country code for a given country name
  static String getCountryCode(String countryName) {
    final country = countries.firstWhere(
      (c) => c['name'] == countryName,
      orElse: () => {'code': ''},
    );
    return country['code'] ?? '';
  }

  // Get country name for a given country code
  static String getCountryName(String countryCode) {
    final country = countries.firstWhere(
      (c) => c['code'] == countryCode,
      orElse: () => {'name': ''},
    );
    return country['name'] ?? '';
  }

  // Get localized country name for a given country code
  static String getLocalizedCountryName(String countryCode, String locale) {
    // Default to English if locale is not supported
    final languageCode = locale.split('_')[0];
    final supportedLocale =
        localizedCountryNames.containsKey(languageCode) ? languageCode : 'en';

    // Get the localized name or fall back to English
    final localizedName = localizedCountryNames[supportedLocale]?[countryCode];
    if (localizedName != null && localizedName.isNotEmpty) {
      return localizedName;
    }

    // Fall back to English if not found
    return localizedCountryNames['en']?[countryCode] ??
        getCountryName(countryCode);
  }

  // Get all country names in the specified locale
  static List<Map<String, String>> getLocalizedCountries(String locale) {
    final languageCode = locale.split('_')[0];
    final supportedLocale =
        localizedCountryNames.containsKey(languageCode) ? languageCode : 'en';

    return countries.map((country) {
      final code = country['code'] as String;
      final localizedName =
          localizedCountryNames[supportedLocale]?[code] ??
          localizedCountryNames['en']?[code] ??
          country['name'] as String;

      return {'code': code, 'name': localizedName};
    }).toList();
  }
}
